<?php

namespace Database\Seeders;

use App\Models\Chemical;
use App\Models\ChemicalCategory;
use App\Models\ChemicalLocation;
use App\Models\User;
use App\Services\QRCodeService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ChemicalSeeder extends Seeder
{
    public function run(): void
    {
        $admin   = User::where('email', 'admin@example.com')->first();
        $manager = User::where('email', 'manager@example.com')->first();

        $solvents  = ChemicalCategory::where('name', 'Solvents')->first();
        $acids     = ChemicalCategory::where('name', 'Acids')->first();
        $bases     = ChemicalCategory::where('name', 'Bases')->first();
        $oxidizers = ChemicalCategory::where('name', 'Oxidizers')->first();
        $reagents  = ChemicalCategory::where('name', 'Reagents')->first();

        $labA     = ChemicalLocation::where('name', 'Laboratory A')->first();
        $labB     = ChemicalLocation::where('name', 'Laboratory B')->first();
        $storage1 = ChemicalLocation::where('name', 'Storage Room 1')->first();
        $storage2 = ChemicalLocation::where('name', 'Storage Room 2')->first();
        $coldRoom = ChemicalLocation::where('name', 'Cold Room')->first();

        $chemicals = [
            [
                'chemical_code'     => 'CHM-0001',
                'chemical_name'     => 'Acetone',
                'cas_number'        => '67-64-1',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'ACS-32201',
                'batch_number'      => 'BT2024-001',
                'lot_number'        => 'LT-20240115',
                'concentration'     => '99.8%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 45.5,
                'minimum_stock'     => 10.0,
                'maximum_stock'     => 100.0,
                'storage_condition' => 'Store below 25°C, away from ignition sources',
                'hazard_class'      => 'Flammable Liquid',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(3),
                'expiry_date'       => now()->addMonths(21),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0002',
                'chemical_name'     => 'Ethanol',
                'cas_number'        => '64-17-5',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'ETH-64175',
                'batch_number'      => 'BT2024-002',
                'lot_number'        => 'LT-20240120',
                'concentration'     => '96%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 8.0,
                'minimum_stock'     => 10.0,
                'maximum_stock'     => 50.0,
                'storage_condition' => 'Store below 25°C, flammable storage area',
                'hazard_class'      => 'Flammable Liquid',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(4),
                'expiry_date'       => now()->addMonths(8),
                'status'            => 'LOW',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0003',
                'chemical_name'     => 'Methanol',
                'cas_number'        => '67-56-1',
                'category_id'       => $solvents->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'M/4000/17',
                'batch_number'      => 'BT2024-003',
                'lot_number'        => 'LT-20240205',
                'concentration'     => '99.9%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 2.5,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 30.0,
                'storage_condition' => 'Store in ventilated flammable storage cabinet',
                'hazard_class'      => 'Toxic, Flammable',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(6),
                'expiry_date'       => now()->addDays(20),
                'status'            => 'CRITICAL',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0004',
                'chemical_name'     => 'Hydrochloric Acid',
                'cas_number'        => '7647-01-0',
                'category_id'       => $acids->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'HCL-258148',
                'batch_number'      => 'BT2024-004',
                'lot_number'        => 'LT-20240110',
                'concentration'     => '37%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 18.0,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 50.0,
                'storage_condition' => 'Store in acid cabinet, away from bases',
                'hazard_class'      => 'Corrosive',
                'location_id'       => $labA->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addMonths(18),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0005',
                'chemical_name'     => 'Sulfuric Acid',
                'cas_number'        => '7664-93-9',
                'category_id'       => $acids->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'SA-258105',
                'batch_number'      => 'BT2024-005',
                'lot_number'        => 'LT-20240118',
                'concentration'     => '95-98%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 12.0,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 40.0,
                'storage_condition' => 'Store in acid-resistant cabinet at room temperature',
                'hazard_class'      => 'Corrosive, Oxidizer',
                'location_id'       => $labA->id,
                'received_date'     => now()->subMonths(5),
                'expiry_date'       => now()->addMonths(24),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0006',
                'chemical_name'     => 'Sodium Hydroxide',
                'cas_number'        => '1310-73-2',
                'category_id'       => $bases->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'S/4920/53',
                'batch_number'      => 'BT2024-006',
                'lot_number'        => 'LT-20240201',
                'concentration'     => '97%',
                'physical_state'    => 'solid',
                'unit'              => 'kg',
                'current_stock'     => 4.8,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 25.0,
                'storage_condition' => 'Store in dry location, away from moisture and acids',
                'hazard_class'      => 'Corrosive',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(3),
                'expiry_date'       => now()->addMonths(30),
                'status'            => 'LOW',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0007',
                'chemical_name'     => 'Potassium Permanganate',
                'cas_number'        => '7722-64-7',
                'category_id'       => $oxidizers->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'KP-223468',
                'batch_number'      => 'BT2024-007',
                'lot_number'        => 'LT-20240125',
                'concentration'     => '99%',
                'physical_state'    => 'solid',
                'unit'              => 'g',
                'current_stock'     => 250.0,
                'minimum_stock'     => 100.0,
                'maximum_stock'     => 1000.0,
                'storage_condition' => 'Store in cool, dry place, away from combustibles',
                'hazard_class'      => 'Oxidizer',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addMonths(36),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0008',
                'chemical_name'     => 'Ammonium Hydroxide',
                'cas_number'        => '1336-21-6',
                'category_id'       => $bases->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'AH-221228',
                'batch_number'      => 'BT2024-008',
                'lot_number'        => 'LT-20240208',
                'concentration'     => '28-30%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 6.5,
                'minimum_stock'     => 3.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in ventilated area, refrigerate if possible',
                'hazard_class'      => 'Corrosive, Toxic',
                'location_id'       => $labB->id,
                'received_date'     => now()->subMonths(1),
                'expiry_date'       => now()->addMonths(12),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0009',
                'chemical_name'     => 'Nitric Acid',
                'cas_number'        => '7697-37-2',
                'category_id'       => $acids->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'NA-438073',
                'batch_number'      => 'BT2024-009',
                'lot_number'        => 'LT-20240112',
                'concentration'     => '65%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 9.5,
                'minimum_stock'     => 3.0,
                'maximum_stock'     => 30.0,
                'storage_condition' => 'Store in acid cabinet, away from organic materials',
                'hazard_class'      => 'Corrosive, Oxidizer',
                'location_id'       => $labA->id,
                'received_date'     => now()->subMonths(4),
                'expiry_date'       => now()->addMonths(15),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0010',
                'chemical_name'     => 'Isopropyl Alcohol',
                'cas_number'        => '67-63-0',
                'category_id'       => $solvents->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'IPA-I9516',
                'batch_number'      => 'BT2024-010',
                'lot_number'        => 'LT-20240220',
                'concentration'     => '99.5%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 32.0,
                'minimum_stock'     => 8.0,
                'maximum_stock'     => 60.0,
                'storage_condition' => 'Store below 25°C in flammable storage',
                'hazard_class'      => 'Flammable Liquid',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(1),
                'expiry_date'       => now()->addMonths(20),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0011',
                'chemical_name'     => 'Chloroform',
                'cas_number'        => '67-66-3',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'CF-288306',
                'batch_number'      => 'BT2023-011',
                'lot_number'        => 'LT-20231015',
                'concentration'     => '99%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 0.8,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 15.0,
                'storage_condition' => 'Store in dark, cool place; light-sensitive',
                'hazard_class'      => 'Toxic, Carcinogen',
                'location_id'       => $coldRoom->id,
                'received_date'     => now()->subMonths(12),
                'expiry_date'       => now()->subDays(15),
                'status'            => 'EXPIRED',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0012',
                'chemical_name'     => 'Acetic Acid',
                'cas_number'        => '64-19-7',
                'category_id'       => $acids->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'AA-695092',
                'batch_number'      => 'BT2024-012',
                'lot_number'        => 'LT-20240301',
                'concentration'     => '99.7%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 22.0,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 40.0,
                'storage_condition' => 'Store at room temperature, away from oxidizers',
                'hazard_class'      => 'Flammable, Corrosive',
                'location_id'       => $labB->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addMonths(22),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0013',
                'chemical_name'     => 'Sodium Chloride',
                'cas_number'        => '7647-14-5',
                'category_id'       => $reagents->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'SC-S271-3',
                'batch_number'      => 'BT2024-013',
                'lot_number'        => 'LT-20240315',
                'concentration'     => '99.5%',
                'physical_state'    => 'solid',
                'unit'              => 'kg',
                'current_stock'     => 8.5,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in dry location at room temperature',
                'hazard_class'      => 'Non-hazardous',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(3),
                'expiry_date'       => now()->addMonths(48),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0014',
                'chemical_name'     => 'Hydrogen Peroxide',
                'cas_number'        => '7722-84-1',
                'category_id'       => $oxidizers->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'HP-H1009',
                'batch_number'      => 'BT2024-014',
                'lot_number'        => 'LT-20240210',
                'concentration'     => '30%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 3.5,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in cool, dark place; refrigerate after opening',
                'hazard_class'      => 'Oxidizer, Corrosive',
                'location_id'       => $coldRoom->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addDays(25),
                'status'            => 'EXPIRING_SOON',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0015',
                'chemical_name'     => 'Phosphoric Acid',
                'cas_number'        => '7664-38-2',
                'category_id'       => $acids->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'PA-A242-500',
                'batch_number'      => 'BT2024-015',
                'lot_number'        => 'LT-20240322',
                'concentration'     => '85%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 15.0,
                'minimum_stock'     => 3.0,
                'maximum_stock'     => 30.0,
                'storage_condition' => 'Store in cool, dry place in acid-resistant container',
                'hazard_class'      => 'Corrosive',
                'location_id'       => $labA->id,
                'received_date'     => now()->subMonths(1),
                'expiry_date'       => now()->addMonths(36),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0016',
                'chemical_name'     => 'Diethyl Ether',
                'cas_number'        => '60-29-7',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'DE-296082',
                'batch_number'      => 'BT2024-016',
                'lot_number'        => 'LT-20240401',
                'concentration'     => '99.5%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 5.0,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in explosion-proof refrigerator',
                'hazard_class'      => 'Extremely Flammable',
                'location_id'       => $coldRoom->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addMonths(6),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0017',
                'chemical_name'     => 'Toluene',
                'cas_number'        => '108-88-3',
                'category_id'       => $solvents->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'TOL-T290-4',
                'batch_number'      => 'BT2024-017',
                'lot_number'        => 'LT-20240415',
                'concentration'     => '99.9%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 18.5,
                'minimum_stock'     => 5.0,
                'maximum_stock'     => 50.0,
                'storage_condition' => 'Store in flammable storage away from oxidizers',
                'hazard_class'      => 'Flammable, Toxic',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(3),
                'expiry_date'       => now()->addMonths(18),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0018',
                'chemical_name'     => 'Potassium Hydroxide',
                'cas_number'        => '1310-58-3',
                'category_id'       => $bases->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'KH-221473',
                'batch_number'      => 'BT2024-018',
                'lot_number'        => 'LT-20240420',
                'concentration'     => '90%',
                'physical_state'    => 'solid',
                'unit'              => 'kg',
                'current_stock'     => 3.2,
                'minimum_stock'     => 4.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in dry, sealed container away from CO2',
                'hazard_class'      => 'Corrosive',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(4),
                'expiry_date'       => now()->addMonths(24),
                'status'            => 'LOW',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0019',
                'chemical_name'     => 'Benzene',
                'cas_number'        => '71-43-2',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'BZ-270709',
                'batch_number'      => 'BT2024-019',
                'lot_number'        => 'LT-20240501',
                'concentration'     => '99.8%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 0.5,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 10.0,
                'storage_condition' => 'Store in explosion-proof cabinet; carcinogen',
                'hazard_class'      => 'Flammable, Carcinogen',
                'location_id'       => $storage2->id,
                'received_date'     => now()->subMonths(10),
                'expiry_date'       => now()->addDays(10),
                'status'            => 'CRITICAL',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0020',
                'chemical_name'     => 'Calcium Chloride',
                'cas_number'        => '10043-52-4',
                'category_id'       => $reagents->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'CC-C77-500',
                'batch_number'      => 'BT2024-020',
                'lot_number'        => 'LT-20240510',
                'concentration'     => '97%',
                'physical_state'    => 'solid',
                'unit'              => 'kg',
                'current_stock'     => 12.0,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 30.0,
                'storage_condition' => 'Store in tightly closed container to prevent moisture absorption',
                'hazard_class'      => 'Irritant',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(2),
                'expiry_date'       => now()->addMonths(48),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
            [
                'chemical_code'     => 'CHM-0021',
                'chemical_name'     => 'Dichloromethane',
                'cas_number'        => '75-09-2',
                'category_id'       => $solvents->id,
                'supplier'          => 'Sigma-Aldrich',
                'manufacturer'      => 'Merck KGaA',
                'catalog_number'    => 'DCM-270997',
                'batch_number'      => 'BT2024-021',
                'lot_number'        => 'LT-20240515',
                'concentration'     => '99.8%',
                'physical_state'    => 'liquid',
                'unit'              => 'L',
                'current_stock'     => 11.0,
                'minimum_stock'     => 3.0,
                'maximum_stock'     => 25.0,
                'storage_condition' => 'Store in cool, well-ventilated area away from light',
                'hazard_class'      => 'Toxic',
                'location_id'       => $labB->id,
                'received_date'     => now()->subMonths(1),
                'expiry_date'       => now()->addMonths(14),
                'status'            => 'SAFE',
                'created_by'        => $admin->id,
            ],
            [
                'chemical_code'     => 'CHM-0022',
                'chemical_name'     => 'Sodium Carbonate',
                'cas_number'        => '497-19-8',
                'category_id'       => $bases->id,
                'supplier'          => 'Fisher Scientific',
                'manufacturer'      => 'Thermo Fisher Scientific',
                'catalog_number'    => 'SC-S263-500',
                'batch_number'      => 'BT2024-022',
                'lot_number'        => 'LT-20240520',
                'concentration'     => '99.5%',
                'physical_state'    => 'solid',
                'unit'              => 'kg',
                'current_stock'     => 7.5,
                'minimum_stock'     => 2.0,
                'maximum_stock'     => 20.0,
                'storage_condition' => 'Store in sealed container to prevent CO2 absorption',
                'hazard_class'      => 'Irritant',
                'location_id'       => $storage1->id,
                'received_date'     => now()->subMonths(3),
                'expiry_date'       => now()->addMonths(60),
                'status'            => 'SAFE',
                'created_by'        => $manager->id,
            ],
        ];

        $qrService = app(QRCodeService::class);
        foreach ($chemicals as $chemical) {
            $created = Chemical::updateOrCreate(
                ['chemical_code' => $chemical['chemical_code']],
                $chemical
            );
            $qrPath = $qrService->generate($created->chemical_code, $qrService->buildContent($created->chemical_code));
            $created->updateQuietly(['qr_code' => $qrPath]);
        }
    }
}
