<?php

namespace Database\Seeders;

use App\Models\Chemical;
use App\Models\ChemicalDailyUsage;
use App\Models\ChemicalLogDate;
use App\Models\ChemicalMonthlyBalance;
use App\Models\User;
use Illuminate\Database\Seeder;

class MonthlyBalanceSeeder extends Seeder
{
    /**
     * Seed monthly balance data from Google Sheets:
     * - Database Maret  (2026-03)
     * - Database Aprill (2026-04)
     * - Database Mei    (2026-05)
     * - Juni            (2026-06)
     * - Juli            (2026-07)
     */
    public function run(): void
    {
        $admin = User::where('role', 'ADMIN')->first() ?? User::first();

        // DATA STRUCTURE per entry: [name, unit, saldo_awal, penerimaan, usages]
        // usages: ['YYYY-MM-DD' => [take1, take2, take3, analyst]]

        $months = $this->getMonthData();

        $this->command->info('Starting MonthlyBalanceSeeder...');

        foreach ($months as $period => $chemicals) {
            $this->command->info("Processing period: $period (" . count($chemicals) . " chemicals)");
            $count = 0;

            foreach ($chemicals as $row) {
                [$chemName, $unit, $saldoAwal, $penerimaan, $usages] = $row;

                $chemical = $this->findChemical($chemName, $unit);

                if (!$chemical) {
                    $this->command->warn("  Chemical not found: $chemName");
                    continue;
                }

                ChemicalMonthlyBalance::updateOrCreate(
                    ['chemical_id' => $chemical->id, 'period_month' => $period],
                    [
                        'saldo_awal' => $saldoAwal !== null ? (float)$saldoAwal : 0,
                        'penerimaan' => (float)$penerimaan,
                    ]
                );

                foreach ($usages as $date => $takeData) {
                    [$take1, $take2, $take3, $analyst] = $takeData;

                    $logDate = ChemicalLogDate::whereDate('log_date', $date)
                        ->where('analyst_name', $analyst)
                        ->first();

                    if (!$logDate) {
                        $logDate = ChemicalLogDate::create([
                            'log_date'     => $date,
                            'analyst_name' => $analyst,
                            'period_month' => substr($date, 0, 7),
                            'created_by'   => $admin?->id,
                        ]);
                    }

                    ChemicalDailyUsage::updateOrCreate(
                        ['chemical_id' => $chemical->id, 'log_date_id' => $logDate->id],
                        ['take_1' => $take1, 'take_2' => $take2, 'take_3' => $take3, 'updated_by' => $admin?->id]
                    );
                }

                $count++;
            }

            $this->command->info("  Done: $count chemicals processed for $period");
        }

        $this->command->info('MonthlyBalanceSeeder completed!');
    }

    private function findChemical(string $name, ?string $unit = null): ?Chemical
    {
        $name = trim($name);

        $chem = Chemical::where('chemical_name', $name)->first();
        if ($chem) return $chem;

        // Try LIKE match on first 30 chars
        $prefix = substr($name, 0, 30);
        $chem = Chemical::where('chemical_name', 'LIKE', $prefix . '%')->first();
        if ($chem) return $chem;

        // Try with partial match
        $words = explode(' ', $name);
        if (count($words) >= 2) {
            $partial = $words[0] . ' ' . $words[1];
            $chem = Chemical::where('chemical_name', 'LIKE', '%' . $partial . '%')->first();
        }

        return $chem;
    }

    private function getMonthData(): array
    {
        return [
            // ══════════════════════════════════════════════════════
            // MARET 2026
            // ══════════════════════════════════════════════════════
            '2026-03' => [
                ['1,10 - phenanthroline chloride monohydrate',  'g',   20,    0, []],
                ['1,10 - phenanthroline monohydrate',           'g',   1.1,   0, []],
                ['1,8-Dihydroxy-2-(4-Sulfophenylazo)-naphthalene-3,6-disulfonic acid trisodium salt','g',5,0,[]],
                ['1,5-Diphenylcarbazide',                       'g',   40,    0, []],
                ['1-Amino-2-hydroxide-4-naphtalene sulforic acid','g', 20,    0, []],
                ['1-Butanol',                                   'ml',  2500,  0, []],
                ['1-Naphtholbenzine',                           'g',   2,     0, []],
                ['4-amino-2,3-dimethyl-1phenyl-3-pyrazolin-5-one','g', 3,    0, []],
                ['Acetic acid (glacial) 100%',                  'ml',  13500, 0, []],
                ['Acetone',                                     'ml',  3500,  0, []],
                ['Alizarin -3- methylamine-N,N diacetic acid dihydrate','g',1,0,[]],
                ['Alizarin Red indicator',                      'g',   24,    0, []],
                ['Alkylbenzyl dimethylammonium chloride',        'g',   200,   0, []],
                ['Aluminium hydroxide',                         'g',   1950,  0, []],
                ['Aluminium kalium sulfat dodecahydrat',        'g',   500,   0, []],
                ['Amidosulfuris acid',                          'g',   160,   0, []],
                ['Ammonia solution 25 %',                       'ml',  2000,  0, ['2026-03-12'=>[142.5,null,null,'Nur Janah']]],
                ['Ammonium acetate',                            'g',   1750,  0, []],
                ['Ammonium fluoride',                           'g',   240,   0, []],
                ['Ammonium heptamolybdate tetrahydrate',        'g',   500,   0, []],
                ['Ammonium iron (III) sulfate dodecahydrate',   'g',   12080, 0, []],
                ['Amonium chloride',                            'g',   1000,  0, ['2026-03-12'=>[16.125,16.125,16.125,'Tyas'],'2026-03-13'=>[16.125,null,null,'Tyas']]],
                ['Amonium monovanadate',                        'g',   197,   0, []],
                ['Asam salisilat teknis',                       'g',   302,   0, []],
                ['Asam sulfamat',                               'g',   3,     0, []],
                ['Barbituric acid',                             'g',   3,     0, []],
                ['Barium acetat',                               'g',   200,   0, []],
                ['Barium chloride dihydrate',                   null,  null,  0, []],
                ['Biuret wasserfrei',                           null,  null,  0, []],
                ['Boric acid',                                  'g',   500,   0, []],
                ['Bromocresol green indicator',                 'g',   7,     0, []],
                ['Brucine',                                     'g',   120,   0, []],
                ['Cadmium sulfat hydrate',                      'g',   120,   0, []],
                ['Calcium carbonate',                           'g',   250,   0, []],
                ['Calcium hypochlorite',                        'g',   80,    0, []],
                ['Cerium (III) nitratehex-hydrate',             'g',   30,    0, []],
                ['Chloramin T trihydrate',                      'g',   470,   0, []],
                ['Chloroform',                                  null,  null,  0, []],
                ['Chromatropic Acid disodium salt',             'g',   44,    0, []],
                ['Chromium (VI) oxide',                         'g',   370,   0, []],
                ['Citric acid monohydrate',                     'g',   500,   0, []],
                ['Cobalt (II) chloride hexahydrate',            'g',   90,    0, []],
                ['Copper (II) sulfate pentahydrate',            'g',   1700,  0, ['2026-03-01'=>[2.0612,null,null,'Fitria']]],
                ['Curcumine',                                   'g',   3,     0, []],
                ['Cyclohexane',                                 'ml',  5000,  0, []],
                ['D (+) Glucose anhydrous for biochemistry',    null,  null,  0, []],
                ['Devarda alloy',                               'g',   370,   0, []],
                ['Di-ammonium oxalate monohydrate',             'g',   462,   0, []],
                ['Di-amonium hydrogen phosphate',               'g',   450,   0, []],
                ['Dikalium hydrogen phosphat',                  'g',   600,   0, []],
                ['Dimedone',                                    'g',   49,    0, []],
                ['Disodium hydrogen phosphate dodecahydrate',   'g',   500,   0, []],
                ['Disodium hydrogen phosphate heptahydrate',    'g',   150,   0, []],
                ['Di-sodium oxalate',                           'g',   250,   0, []],
                ['Dodecyl sulfate sodium salt',                 'g',   180,   0, []],
                ['Eisen (II) sulfate-heptahydrat',             null,  null,  0, []],
                ['Eosin Y (Yellowish) CI 45380',               'g',   15,    0, []],
                ['Erichrome cyanine R CI 4380',                'g',   25,    0, []],
                ['Ethanol',                                     'ml',  11200, 0, ['2026-03-19'=>[1000,null,null,'Tyas']]],
                ['Ethanol absolut',                             'ml',  200,   0, []],
                ['Ferroin indicator solution',                  null,  null,  0, []],
                ['Formaldehyde solution 37%',                   null,  null,  0, []],
                ['Gelatine',                                    'g',   950,   0, []],
                ['Hexamethylene-tetramine',                     'g',   100,   0, []],
                ['Hydrazinium sulfate',                         'g',   170,   0, []],
                ['Hydrochloric acid 37%',                       'ml',  18500, 0, ['2026-03-13'=>[10,null,null,'Tyas'],'2026-03-14'=>[10,5,null,'Tyas']]],
                ['Hydrochloric acid fuming 37%',                'ml',  5000,  0, []],
                ['Hydrogen peroxide 30%',                       'ml',  2500,  0, []],
                ['Hydroxlamine hydrochloride',                  null,  null,  0, []],
                ['Hydroxylammonium chloride',                   'g',   220,   0, []],
                ['Hydroxylammonium sulfate',                    'g',   400,   0, []],
                ['Indigocarmin',                                'g',   25,    0, []],
                ['Iodine',                                      'g',   160,   0, []],
                ['Iron (III) Chloride',                         'g',   70,    0, []],
                ['Iron (II) Sulfate Heptahydrate',              'g',   100,   0, []],
                ['Iron test',                                   'test',300,   0, []],
                ['Isoamyl alkohol',                             'ml',  900,   0, []],
                ['Isobutyl methyl ketone',                      null,  null,  0, []],
                ['Kalium bromat',                               'g',   50,    0, []],
                ['Kalium chlorat',                              'g',   300,   0, []],
                ['Kalium iodidat',                              null,  null,  0, []],
                ['Kaliumantimon (III)-oxidtartrat-hemihydrat',  'g',   200,   0, []],
                ['L (+) Asorbic Acid',                         'g',   235,   0, []],
                ['Lanthanum (III) chloride heptahydrate 98%',  'g',   80,    0, []],
                ['Lanthanum nitrate hexahydrate',               'g',   10,    0, []],
                ['Lead (II) acetate trihydrate',                'g',   230,   0, []],
                ['Lead (II) oxide',                             'g',   250,   0, []],
                ['L-Histidine monohydrate chloride monohydrate',null,  null,  0, []],
                ['Magnesium (II) sulfate monohydrate',          null,  null,  0, []],
                ['Magnesium chloride hexahydrate',              'g',   800,   0, []],
                ['Magnesium oxide',                             'g',   80,    0, []],
                ['Manganese (II) Sulfate Monohydrate',          'g',   253,   0, []],
                ['Manganese test',                              null,  null,  0, []],
                ['Mercury (II) chloride',                       'g',   10,    0, []],
                ['Mercury (II) iodide',                         'g',   40,    0, []],
                ['Mercury (II) oxide',                          'g',   40,    0, []],
                ['Mercury (II) sulfate',                        'g',   500,   0, []],
                ['Mercury (II) thiocyanate',                    'g',   25,    0, []],
                ['Methanol',                                    'ml',  2500,  0, []],
                ['Methyl Purple Indicator Solution 1 g/L',      'ml',  500,   0, []],
                ['Methyl red (CI 13020)',                       'g',   35,    0, []],
                ['Methyl red sodium salt (CI 13020)',           'g',   44,    0, []],
                ['Methylenblue',                                'g',   50,    0, []],
                ['N-(1-Naphythyl) ethylenediamine dihydro-chloride','g',180,  0, []],
                ['N,N-diethyl-1,4 phenyle diammonium sulfat',  'g',   200,   0, []],
                ['N,N-dimethyl-1,4 phenylene diamonium dichloride','g',50,    0, []],
                ['N,N-Dimethyl-1,4 phenyl-enediamine oxalate', null,  null,  0, []],
                ['n-Amylalkohol',                               'ml',  900,   0, []],
                ['Naphtholbenzein',                             'g',   3,     0, []],
                ['Natrium fluoride',                            'g',   250,   0, []],
                ['Natrium molibdat.dihidrat',                   'g',   30,    0, []],
                ['n-heptane',                                   null,  null,  0, []],
                ['n-Hexadecane',                                'ml',  500,   0, []],
                ['Nickel (II) nitrate hexahydrate',             'g',   100,   0, []],
                ['Nitric acid 65%',                             'ml',  8500,  0, ['2026-03-10'=>[25,21,4,'Tyas'],'2026-03-11'=>[25,null,null,'Tyas'],'2026-03-13'=>[50,null,null,'Tyas'],'2026-03-14'=>[50,null,null,'Tyas']]],
                ['Ortho-Phosphoric acid 85%',                   null,  null,  0, []],
                ['Oxalic acid dihydrate',                       'g',   500,   0, []],
                ['Pararosanline (chloride) CI 42500',           null,  null,  0, []],
                ['Perochloric acid 70-72%',                     'ml',  2000,  0, []],
                ['Phenol',                                      'g',   100,   0, []],
                ['Phenol Red ( Phenol sulfonphthalein)',         'g',   0.4,   0, []],
                ['Phenol red indicator',                        'g',   3,     0, []],
                ['Phenolphathalein indicator',                  null,  null,  0, []],
                ['Potassium chloride',                          'g',   600,   0, []],
                ['Potassium chromate',                          'g',   830,   0, []],
                ['Potassium cyanide',                           'g',   800,   0, []],
                ['Potassium dichromate',                        'g',   570,   0, []],
                ['Potassium dihydrogen phosphate',              null,  null,  0, []],
                ['Potassium hexacynoferrate (II) trihydrate',   'g',   300,   0, []],
                ['Potassium hexxchloroplatirale (IV)',           'g',   100,   0, []],
                ['Potassium hydrogen phthalate',                'g',   230,   0, []],
                ['Potassium hydroxide',                         null,  null,  0, []],
                ['Potassium Iodide',                            'g',   1200,  0, []],
                ['Potassium nitrate',                           'g',   1900,  0, []],
                ['Potassium permanganat',                       null,  null,  0, []],
                ['Potassium peroxodisulfate',                   'g',   260,   0, []],
                ['Potassium sodium tartrate tetrahydrate',       'g',   1550,  0, []],
                ['Potassium Sulfate',                           'g',   2500,  0, []],
                ['Pyrroliodine-1-dithiocarboxylic acid ammonium salt','g',8,  0, []],
                ['Salicylic Acid',                              null,  null,  0, []],
                ['Selenium reagent mixture',                    'g',   700,   0, ['2026-03-05'=>[0.2194,0.2541,null,'Tyas']]],
                ['Silver nitrate',                              'g',   50,    0, ['2026-03-06'=>[4.259,null,null,'Fitria']]],
                ['Silver sulfate',                              'g',   45,    0, []],
                ['Sodium acetat trihydrate',                    'g',   1300,  0, []],
                ['Sodium azide',                                null,  null,  0, []],
                ['Sodium borohyride',                           'g',   170,   0, []],
                ['Sodium Carbonate',                            'g',   750,   0, []],
                ['Sodium chloride',                             'g',   1600,  0, ['2026-03-05'=>[0.59,null,null,'Tyas']]],
                ['Sodium dihydrogen phospate dihydrate',        'g',   480,   0, []],
                ['Sodium fluoride',                             'g',   250,   0, []],
                ['Sodium hydrogen Carbonate',                   'g',   900,   0, []],
                ['Sodium hydrogen sulfite',                     'ml',  1000,  0, []],
                ['Sodium hydroxide',                            'g',   4000,  0, ['2026-03-03'=>[16.25,null,null,'Fitria']]],
                ['Sodium nitrite',                              'g',   850,   0, []],
                ['Sodium nitroprusside dihydrate',              'g',   160,   0, []],
                ['Sodium sulfate',                              'g',   1500,  0, ['2026-03-01'=>[2.0828,null,null,'Fitria']]],
                ['Sodium sulfite',                              'g',   1000,  0, []],
                ['Sodium tetraborate',                          'g',   340,   0, []],
                ['Sodium tetraphenyl borate',                   'g',   49,    0, []],
                ['Sodium thiosulfate',                          'g',   1024,  0, []],
                ['Starch',                                      null,  null,  0, []],
                ['Stearic acid',                                'g',   1740,  0, []],
                ['Strontium nitrate',                           'g',   150,   0, []],
                ['Sulfanilamide',                               'g',   102,   0, []],
                ['Sulfanilic acid',                             null,  null,  0, []],
                ['Sulphuric acid',                              'ml',  1450,  0, ['2026-03-01'=>[25,null,null,'Fitria']]],
                ['Thiocetamide',                                'g',   45,    0, []],
                ['Tin (II) chloride',                           'g',   500,   0, []],
                ['Titriplex',                                   null,  null,  0, []],
                ['Titriplex I',                                 'g',   100,   0, []],
                ['Titriplex II',                                null,  null,  0, []],
                ['Titriplex III',                               null,  null,  0, []],
                ['Tri-natriumphosphat-dodecahhydrate',          null,  null,  0, []],
                ['Trisodium citrate dihydrate',                 'g',   3000,  0, []],
                ['Tri-Sodium Phosphate dodecahydrat',           'g',   500,   0, []],
                ['Wolframatophosphosaure hydrate',              'g',   40,    0, []],
                ['Xylene',                                      'ml',  15000, 0, []],
                ['Zirkon (IV) Oxidchlorid-Octahydrat',         'g',   105,   0, []],
                ['Zinc acetate dihydrate',                      'g',   170,   0, []],
                ['Zinc sulfate',                                null,  null,  0, []],
                ['Zinc sulfate heptahydrate',                   'g',   900,   0, []],
            ],

            // ══════════════════════════════════════════════════════
            // APRIL 2026
            // ══════════════════════════════════════════════════════
            '2026-04' => [
                ['1,10 - phenanthroline chloride monohydrate',  'g',   20,    0,     []],
                ['1,10 - phenanthroline monohydrate',           'g',   1.1,   0,     []],
                ['1,8-Dihydroxy-2-(4-Sulfophenylazo)-naphthalene-3,6-disulfonic acid trisodium salt','g',5,0,[]],
                ['1,5-Diphenylcarbazide',                       'g',   40,    0,     []],
                ['1-Amino-2-hydroxide-4-naphtalene sulforic acid','g', 20,    0,     []],
                ['1-Butanol',                                   'ml',  2500,  0,     []],
                ['1-Naphtholbenzine',                           'g',   2,     0,     []],
                ['4-amino-2,3-dimethyl-1phenyl-3-pyrazolin-5-one','g', 3,     0,     []],
                ['Acetic acid (glacial) 100%',                  'ml',  13500, 0,     []],
                ['Acetone p.a',                                 'ml',  10000, 10000, []],
                ['Acetone teknis',                              null,  null,  0,     []],
                ['Alizarin -3- methylamine-N,N diacetic acid dihydrate','g',1,0,     []],
                ['Alizarin Red indicator',                      'g',   24,    0,     []],
                ['Alkylbenzyl dimethylammonium chloride',        'g',   200,   0,     []],
                ['Alumunium foil',                              null,  null,  0,     []],
                ['Aluminium hydroxide',                         'g',   1950,  0,     []],
                ['Aluminium kalium sulfat dodecahydrat',        'g',   500,   0,     []],
                ['Amidosulfuris acid',                          'g',   160,   0,     []],
                ['Ammonia solution 25 %',                       'ml',  1857.5,0,     []],
                ['Ammonium acetate',                            'g',   1750,  0,     []],
                ['Ammonium fluoride',                           'g',   240,   0,     []],
                ['Ammonium heptamolybdate tetrahydrate',        'g',   500,   0,     []],
                ['Ammonium iron (III) sulfate dodecahydrate',   'g',   12080, 0,     []],
                ['Amonium chloride',                            'g',   935.5, 0,     []],
                ['Amonium monovanadate',                        'g',   197,   0,     []],
                ['Aquabides',                                   'ml',  15000, 15000, []],
                ['Asam salisilat teknis',                       'g',   302,   0,     []],
                ['Asam sulfamat',                               'g',   3,     0,     []],
                ['Barbituric acid',                             'g',   3,     0,     []],
                ['Barium acetat',                               'g',   200,   0,     []],
                ['Barium chloride dihydrate',                   null,  null,  15,    ['2026-04-17'=>[15,null,null,'Tyas']]],
                ['Biuret wasserfrei',                           null,  null,  0,     []],
                ['Boric acid',                                  'g',   500,   0,     []],
                ['Bromocresol green indicator',                 'g',   7,     0,     []],
                ['Brucine',                                     'g',   120,   0,     []],
                ['Cadmium sulfat hydrate',                      'g',   120,   0,     []],
                ['Calcium carbonate',                           'g',   250,   0,     []],
                ['Calcium hypochlorite',                        'g',   80,    0,     []],
                ['Cerium (III) nitratehex-hydrate',             'g',   30,    0,     []],
                ['Chloramin T trihydrate',                      'g',   470,   0,     []],
                ['Chloroform',                                  null,  null,  0,     []],
                ['Chromatropic Acid disodium salt',             'g',   44,    0,     []],
                ['Chromium (VI) oxide',                         'g',   370,   0,     []],
                ['Citric acid monohydrate',                     'g',   500,   0,     []],
                ['Cobalt (II) chloride hexahydrate',            'g',   90,    0,     []],
                ['Copper (II) sulfate pentahydrate',            'g',   1697.94,0,    ['2026-04-08'=>[2.0016,null,null,'Alya']]],
                ['Curcumine',                                   'g',   3,     0,     []],
                ['Cyclohexane',                                 'ml',  5000,  0,     []],
                ['D (+) Glucose anhydrous for biochemistry',    null,  null,  0,     []],
                ['Devarda alloy',                               'g',   370,   0,     []],
                ['Di-ammonium oxalate monohydrate',             'g',   462,   0,     []],
                ['Di-amonium hydrogen phosphate',               'g',   450,   0,     []],
                ['Dikalium hydrogen phosphat',                  'g',   600,   0,     []],
                ['Dimedone',                                    'g',   49,    0,     []],
                ['Disodium hydrogen phosphate dodecahydrate',   'g',   500,   0,     []],
                ['Disodium hydrogen phosphate heptahydrate',    'g',   150,   0,     []],
                ['Di-sodium oxalate',                           'g',   250,   0,     []],
                ['Dodecyl sulfate sodium salt',                 'g',   180,   0,     []],
                ['Eisen (II) sulfate-heptahydrat',             null,  null,  0,     []],
                ['Eosin Y (Yellowish) CI 45380',               'g',   15,    0,     []],
                ['Erichrome cyanine R CI 4380',                'g',   25,    0,     []],
                ['Ethanol',                                     'ml',  10200, 0,     []],
                ['Ethanol absolut',                             'ml',  200,   0,     []],
                ['Ferroin indicator solution',                  null,  null,  0,     []],
                ['Formaldehyde solution 37%',                   null,  null,  0,     []],
                ['Gelatine',                                    'g',   950,   0,     []],
                ['Hexamethylene-tetramine',                     'g',   100,   0,     []],
                ['Hydrazinium sulfate',                         'g',   170,   0,     []],
                ['Hydrochloric acid 37%',                       'ml',  18475, 20,    ['2026-04-10'=>[10,10,null,'Tyas']]],
                ['Hydrochloric acid fuming 37%',                'ml',  5000,  0,     []],
                ['Hydrogen peroxide 30%',                       'ml',  2500,  0,     []],
                ['Hydroxlamine hydrochloride',                  null,  null,  0,     []],
                ['Hydroxylammonium chloride',                   'g',   220,   0,     []],
                ['Hydroxylammonium sulfate',                    'g',   400,   0,     []],
                ['Indigocarmin',                                'g',   25,    0,     []],
                ['Iodine',                                      'g',   160,   0,     []],
                ['Iron (III) Chloride',                         'g',   70,    0,     []],
                ['Iron (II) Sulfate Heptahydrate',              'g',   100,   0,     []],
                ['Iron test',                                   'test',300,   0,     []],
                ['Isoamyl alkohol',                             'ml',  900,   0,     []],
                ['Isobutyl methyl ketone',                      null,  null,  0,     []],
                ['Kalium bromat',                               'g',   50,    0,     []],
                ['Kalium chlorat',                              'g',   300,   0,     []],
                ['Kalium iodidat',                              null,  null,  0,     []],
                ['Kaliumantimon (III)-oxidtartrat-hemihydrat',  'g',   200,   0,     []],
                ['L (+) Asorbic Acid',                         'g',   235,   0,     []],
                ['Lanthanum (III) chloride heptahydrate 98%',  'g',   80,    0,     []],
                ['Lanthanum nitrate hexahydrate',               'g',   10,    0,     []],
                ['Lead (II) acetate trihydrate',                'g',   230,   0,     []],
                ['Lead (II) oxide',                             'g',   250,   0,     []],
                ['L-Histidine monohydrate chloride monohydrate',null,  null,  0,     []],
                ['Magnesium (II) sulfate monohydrate',          null,  null,  0,     []],
                ['Magnesium chloride hexahydrate',              'g',   800,   0,     []],
                ['Magnesium oxide',                             'g',   80,    4,     ['2026-04-18'=>[4,null,null,'Jihan']]],
                ['Manganese (II) Sulfate Monohydrate',          'g',   253,   0,     []],
                ['Manganese test',                              null,  null,  0,     []],
                ['Mercury (II) chloride',                       'g',   10,    0,     []],
                ['Mercury (II) iodide',                         'g',   40,    0,     []],
                ['Mercury (II) oxide',                          'g',   40,    0,     []],
                ['Mercury (II) sulfate',                        'g',   500,   0,     []],
                ['Mercury (II) thiocyanate',                    'g',   25,    0,     []],
                ['Methanol',                                    'ml',  2500,  0,     []],
                ['Methyl Purple Indicator Solution 1 g/L',      'ml',  500,   0,     []],
                ['Methyl red (CI 13020)',                       'g',   35,    0,     []],
                ['Methyl red sodium salt (CI 13020)',           'g',   44,    0,     []],
                ['Methylenblue',                                'g',   5,     5,     []],
                ['N-(1-Naphythyl) ethylenediamine dihydro-chloride','g',180,  0,    []],
                ['N,N-diethyl-1,4 phenyle diammonium sulfat',  'g',   200,   0,     []],
                ['N,N-dimethyl-1,4 phenylene diamonium dichloride','g',50,    0,    []],
                ['N,N-Dimethyl-1,4 phenyl-enediamine oxalate', null,  null,  0,     []],
                ['n-Amylalkohol',                               'ml',  900,   0,     []],
                ['Naphtholbenzein',                             'g',   3,     0,     []],
                ['Natrium fluoride',                            'g',   250,   0,     []],
                ['Natrium molibdat.dihidrat',                   'g',   30,    0,     []],
                ['n-heptane',                                   null,  null,  0,     []],
                ['n-Hexadecane',                                'ml',  500,   0,     []],
                ['Nickel (II) nitrate hexahydrate',             'g',   100,   0,     []],
                ['Nitric acid 65%',                             'ml',  8325,  10000, ['2026-04-07'=>[250,null,null,'Tyas'],'2026-04-08'=>[120,null,null,'Tyas'],'2026-04-09'=>[25,25,25,'Tyas'],'2026-04-10'=>[25,null,null,'Tyas']]],
                ['Ortho-Phosphoric acid 85%',                   null,  null,  0,     []],
                ['Oxalic acid dihydrate',                       'g',   500,   0,     []],
                ['Pararosanline (chloride) CI 42500',           null,  null,  0,     []],
                ['Perochloric acid 70-72%',                     'ml',  4500,  2500,  []],
                ['Phenol',                                      'g',   100,   0,     []],
                ['Phenol Red ( Phenol sulfonphthalein)',         'g',   0.4,   0,     []],
                ['Phenol red indicator',                        'g',   3,     0,     []],
                ['Phenolphathalein indicator',                  null,  null,  0,     []],
                ['Potassium chloride',                          'g',   600,   0,     []],
                ['Potassium chromate',                          'g',   830,   0,     []],
                ['Potassium cyanide',                           'g',   800,   0,     []],
                ['Potassium dichromate',                        'g',   570,   0,     []],
                ['Potassium dihydrogen phosphate',              null,  null,  0,     []],
                ['Potassium hexacynoferrate (II) trihydrate',   'g',   300,   0,     []],
                ['Potassium hexxchloroplatirale (IV)',           'g',   100,   0,     []],
                ['Potassium hydrogen phthalate',                'g',   230,   0,     []],
                ['Potassium hydroxide',                         null,  null,  60,    ['2026-04-18'=>[60,null,null,'Jihan']]],
                ['Potassium Iodide',                            'g',   1200,  0,     []],
                ['Potassium nitrate',                           'g',   1900,  0,     []],
                ['Potassium permanganat',                       null,  null,  0,     []],
                ['Potassium peroxodisulfate',                   'g',   260,   10,    ['2026-04-19'=>[10,null,null,'Gebrina']]],
                ['Potassium sodium tartrate tetrahydrate',       'g',   1550,  0,     []],
                ['Potassium Sulfate',                           'g',   2500,  0,     []],
                ['Pyrroliodine-1-dithiocarboxylic acid ammonium salt','g',8,  0,    []],
                ['Salicylic Acid',                              null,  null,  0,     []],
                ['Selenium reagent mixture',                    'g',   699.53,1,     ['2026-04-09'=>[0.5,0.5,null,'Tyas']]],
                ['Silver nitrate',                              'g',   45.74, 2.6,   ['2026-04-17'=>[2.6,null,null,'Tyas']]],
                ['Silver sulfate',                              'g',   45,    0,     []],
                ['Sodium acetat trihydrate',                    'g',   1300,  0,     []],
                ['Sodium azide',                                null,  null,  0,     []],
                ['Sodium borohyride',                           'g',   170,   0,     []],
                ['Sodium Carbonate',                            'g',   750,   0,     []],
                ['Sodium chloride',                             'g',   1599.41,0,    []],
                ['Sodium dihydrogen phospate dihydrate',        'g',   480,   0,     []],
                ['Sodium fluoride',                             'g',   250,   0,     []],
                ['Sodium hydrogen Carbonate',                   'g',   900,   0,     []],
                ['Sodium hydrogen sulfite',                     'ml',  1000,  0,     []],
                ['Sodium hydroxide',                            'g',   3983.75,400,  ['2026-04-02'=>[400,null,null,'Fitria']]],
                ['Sodium nitrite',                              'g',   850,   0,     []],
                ['Sodium nitroprusside dihydrate',              'g',   160,   0,     []],
                ['Sodium sulfate',                              'g',   1497.92,2.05, ['2026-04-08'=>[2.05,null,null,'Alya']]],
                ['Sodium sulfite',                              'g',   1000,  0,     []],
                ['Sodium tetraborate',                          'g',   340,   0,     []],
                ['Sodium tetraphenyl borate',                   'g',   74,    25,    []],
                ['Sodium thiosulfate',                          'g',   1000,  1000,  []],
                ['Starch',                                      null,  null,  0,     []],
                ['Stearic acid',                                'g',   1740,  0,     []],
                ['Strontium nitrate',                           'g',   150,   0,     []],
                ['Sulfanilamide',                               'g',   102,   0,     []],
                ['Sulfanilic acid',                             null,  null,  0,     []],
                ['Sulphuric acid',                              'ml',  11425, 10000, ['2026-04-07'=>[500,null,null,'Tyas'],'2026-04-09'=>[25,null,null,'Tyas'],'2026-04-10'=>[16,37.5,null,'Tyas'],'2026-04-20'=>[261,null,null,'Tyas']]],
                ['Thiocetamide',                                'g',   45,    0,     []],
                ['Tin (II) chloride',                           'g',   500,   0,     []],
                ['Titriplex',                                   null,  null,  0,     []],
                ['Titriplex I',                                 'g',   100,   0,     []],
                ['Titriplex II',                                null,  null,  0,     []],
                ['Titriplex III',                               null,  null,  0,     []],
                ['Tri-natriumphosphat-dodecahhydrate',          null,  null,  0,     []],
                ['Trisodium citrate dihydrate',                 'g',   3000,  0,     []],
                ['Tri-Sodium Phosphate dodecahydrat',           'g',   500,   0,     []],
                ['Wolframatophosphosaure hydrate',              'g',   40,    0,     []],
                ['Xylene',                                      'ml',  15000, 0,     []],
                ['Zirkon (IV) Oxidchlorid-Octahydrat',         'g',   105,   0,     []],
                ['Zinc acetate dihydrate',                      'g',   170,   0,     []],
                ['Zinc sulfate',                                null,  null,  0,     []],
                ['Zinc sulfate heptahydrate',                   'g',   900,   0,     []],
            ],

            // ══════════════════════════════════════════════════════
            // MEI 2026
            // ══════════════════════════════════════════════════════
            '2026-05' => [
                ['1,10 - phenanthroline chloride monohydrate',  'g',   20,    0, []],
                ['1,10 - phenanthroline monohydrate',           'g',   1.1,   0, []],
                ['1,8-Dihydroxy-2-(4-Sulfophenylazo)-naphthalene-3,6-disulfonic acid trisodium salt','g',5,0,[]],
                ['1,5-Diphenylcarbazide',                       'g',   40,    0, []],
                ['1-Amino-2-hydroxide-4-naphtalene sulforic acid','g', 20,    0, []],
                ['1-Butanol',                                   'ml',  2500,  0, []],
                ['1-Naphtholbenzine',                           'g',   2,     0, []],
                ['4-amino-2,3-dimethyl-1phenyl-3-pyrazolin-5-one','g', 3,     0, []],
                ['Acetic acid (glacial) 100%',                  'ml',  13500, 0, []],
                ['Acetone p.a',                                 'ml',  10000, 0, []],
                ['Acetone teknis',                              null,  null,  0, []],
                ['Alizarin -3- methylamine-N,N diacetic acid dihydrate','g',1,0,[]],
                ['Alizarin Red indicator',                      'g',   24,    0, []],
                ['Alkylbenzyl dimethylammonium chloride',        'g',   200,   0, []],
                ['Alumunium foil',                              null,  null,  0, []],
                ['Aluminium hydroxide',                         'g',   1950,  0, []],
                ['Aluminium kalium sulfat dodecahydrat',        'g',   500,   0, []],
                ['Amidosulfuris acid',                          'g',   160,   0, []],
                ['Ammonia solution 25 %',                       'ml',  1857.5,0, []],
                ['Ammonium acetate',                            'g',   1750,  0, []],
                ['Ammonium fluoride',                           'g',   240,   0, []],
                ['Ammonium heptamolybdate tetrahydrate',        'g',   500,   0, []],
                ['Ammonium iron (III) sulfate dodecahydrate',   'g',   12080, 0, []],
                ['Amonium chloride',                            'g',   935.5, 0, []],
                ['Amonium monovanadate',                        'g',   197,   0, []],
                ['Aquabides',                                   'ml',  15000, 0, []],
                ['Asam salisilat teknis',                       'g',   302,   0, []],
                ['Asam sulfamat',                               'g',   3,     0, []],
                ['Barbituric acid',                             'g',   3,     0, []],
                ['Barium acetat',                               'g',   200,   0, []],
                ['Barium chloride dihydrate',                   null,  null,  0, []],
                ['Biuret wasserfrei',                           null,  null,  0, []],
                ['Boric acid',                                  'g',   500,   0, []],
                ['Bromocresol green indicator',                 'g',   7,     0, []],
                ['Brucine',                                     'g',   120,   0, []],
                ['Cadmium sulfat hydrate',                      'g',   120,   0, []],
                ['Calcium carbonate',                           'g',   250,   0, []],
                ['Calcium hypochlorite',                        'g',   80,    0, []],
                ['Cerium (III) nitratehex-hydrate',             'g',   30,    0, []],
                ['Chloramin T trihydrate',                      'g',   470,   0, []],
                ['Chloroform',                                  null,  null,  0, []],
                ['Chromatropic Acid disodium salt',             'g',   44,    0, []],
                ['Chromium (VI) oxide',                         'g',   370,   0, []],
                ['Citric acid monohydrate',                     'g',   500,   0, []],
                ['Cobalt (II) chloride hexahydrate',            'g',   90,    0, []],
                ['Copper (II) sulfate pentahydrate',            'g',   1695.94,0,[]],
                ['Curcumine',                                   'g',   3,     0, []],
                ['Cyclohexane',                                 'ml',  5000,  0, []],
                ['D (+) Glucose anhydrous for biochemistry',    null,  null,  0, []],
                ['Devarda alloy',                               'g',   370,   0, []],
                ['Di-ammonium oxalate monohydrate',             'g',   462,   0, []],
                ['Di-amonium hydrogen phosphate',               'g',   450,   0, []],
                ['Dikalium hydrogen phosphat',                  'g',   600,   0, []],
                ['Dimedone',                                    'g',   49,    0, []],
                ['Disodium hydrogen phosphate dodecahydrate',   'g',   500,   0, []],
                ['Disodium hydrogen phosphate heptahydrate',    'g',   150,   0, []],
                ['Di-sodium oxalate',                           'g',   250,   0, []],
                ['Dodecyl sulfate sodium salt',                 'g',   180,   0, []],
                ['Eisen (II) sulfate-heptahydrat',             null,  null,  0, []],
                ['Eosin Y (Yellowish) CI 45380',               'g',   15,    0, []],
                ['Erichrome cyanine R CI 4380',                'g',   25,    0, []],
                ['Ethanol',                                     'ml',  10200, 0, []],
                ['Ethanol absolut',                             'ml',  200,   0, []],
                ['Ferroin indicator solution',                  null,  null,  0, []],
                ['Formaldehyde solution 37%',                   null,  null,  0, []],
                ['Gelatine',                                    'g',   950,   0, []],
                ['Hexamethylene-tetramine',                     'g',   100,   0, []],
                ['Hydrazinium sulfate',                         'g',   170,   0, []],
                ['Hydrochloric acid 37%',                       'ml',  18455, 0, []],
                ['Hydrochloric acid fuming 37%',                'ml',  5000,  0, []],
                ['Hydrogen peroxide 30%',                       'ml',  2500,  0, []],
                ['Hydroxlamine hydrochloride',                  null,  null,  0, []],
                ['Hydroxylammonium chloride',                   'g',   220,   0, []],
                ['Hydroxylammonium sulfate',                    'g',   400,   0, []],
                ['Indigocarmin',                                'g',   25,    0, []],
                ['Iodine',                                      'g',   160,   0, []],
                ['Iron (III) Chloride',                         'g',   70,    0, []],
                ['Iron (II) Sulfate Heptahydrate',              'g',   100,   0, []],
                ['Iron test',                                   'test',300,   0, []],
                ['Isoamyl alkohol',                             'ml',  900,   0, []],
                ['Isobutyl methyl ketone',                      null,  null,  0, []],
                ['Kalium bromat',                               'g',   50,    0, []],
                ['Kalium chlorat',                              'g',   300,   0, []],
                ['Kalium iodidat',                              null,  null,  0, []],
                ['Kaliumantimon (III)-oxidtartrat-hemihydrat',  'g',   200,   0, []],
                ['L (+) Asorbic Acid',                         'g',   235,   0, []],
                ['Lanthanum (III) chloride heptahydrate 98%',  'g',   80,    0, []],
                ['Lanthanum nitrate hexahydrate',               'g',   10,    0, []],
                ['Lead (II) acetate trihydrate',                'g',   230,   0, []],
                ['Lead (II) oxide',                             'g',   250,   0, []],
                ['L-Histidine monohydrate chloride monohydrate',null,  null,  0, []],
                ['Magnesium (II) sulfate monohydrate',          null,  null,  0, []],
                ['Magnesium chloride hexahydrate',              'g',   800,   0, []],
                ['Magnesium oxide',                             'g',   76,    0, []],
                ['Manganese (II) Sulfate Monohydrate',          'g',   253,   0, []],
                ['Manganese test',                              null,  null,  0, []],
                ['Mercury (II) chloride',                       'g',   10,    0, []],
                ['Mercury (II) iodide',                         'g',   40,    0, []],
                ['Mercury (II) oxide',                          'g',   40,    0, []],
                ['Mercury (II) sulfate',                        'g',   500,   0, []],
                ['Mercury (II) thiocyanate',                    'g',   25,    0, []],
                ['Methanol',                                    'ml',  2500,  0, []],
                ['Methyl Purple Indicator Solution 1 g/L',      'ml',  500,   0, []],
                ['Methyl red (CI 13020)',                       'g',   35,    0, []],
                ['Methyl red sodium salt (CI 13020)',           'g',   44,    0, []],
                ['Methylenblue',                                'g',   5,     0, []],
                ['N-(1-Naphythyl) ethylenediamine dihydro-chloride','g',180,  0, []],
                ['N,N-diethyl-1,4 phenyle diammonium sulfat',  'g',   200,   0, []],
                ['N,N-dimethyl-1,4 phenylene diamonium dichloride','g',50,    0, []],
                ['N,N-Dimethyl-1,4 phenyl-enediamine oxalate', null,  null,  0, []],
                ['n-Amylalkohol',                               'ml',  900,   0, []],
                ['Naphtholbenzein',                             'g',   3,     0, []],
                ['Natrium fluoride',                            'g',   250,   0, []],
                ['Natrium molibdat.dihidrat',                   'g',   30,    0, []],
                ['n-heptane',                                   null,  null,  0, []],
                ['n-Hexadecane',                                'ml',  500,   0, []],
                ['Nickel (II) nitrate hexahydrate',             'g',   100,   0, []],
                ['Nitric acid 65%',                             'ml',  17880, 0, []],
                ['Ortho-Phosphoric acid 85%',                   null,  null,  0, []],
                ['Oxalic acid dihydrate',                       'g',   500,   0, []],
                ['Pararosanline (chloride) CI 42500',           null,  null,  0, []],
                ['Perochloric acid 70-72%',                     'ml',  4500,  0, []],
                ['Phenol',                                      'g',   100,   0, []],
                ['Phenol Red ( Phenol sulfonphthalein)',         'g',   0.4,   0, []],
                ['Phenol red indicator',                        'g',   3,     0, []],
                ['Phenolphathalein indicator',                  null,  null,  0, []],
                ['Potassium chloride',                          'g',   600,   0, []],
                ['Potassium chromate',                          'g',   830,   0, []],
                ['Potassium cyanide',                           'g',   800,   0, []],
                ['Potassium dichromate',                        'g',   570,   0, []],
                ['Potassium dihydrogen phosphate',              null,  null,  0, []],
                ['Potassium hexacynoferrate (II) trihydrate',   'g',   300,   0, []],
                ['Potassium hexxchloroplatirale (IV)',           'g',   100,   0, []],
                ['Potassium hydrogen phthalate',                'g',   230,   0, []],
                ['Potassium hydroxide',                         null,  null,  0, []],
                ['Potassium Iodide',                            'g',   1200,  0, []],
                ['Potassium nitrate',                           'g',   1900,  0, []],
                ['Potassium permanganat',                       null,  null,  0, []],
                ['Potassium peroxodisulfate',                   'g',   250,   0, []],
                ['Potassium sodium tartrate tetrahydrate',       'g',   1550,  0, []],
                ['Potassium Sulfate',                           'g',   2500,  0, []],
                ['Pyrroliodine-1-dithiocarboxylic acid ammonium salt','g',8,  0, []],
                ['Salicylic Acid',                              null,  null,  0, []],
                ['Selenium reagent mixture',                    'g',   698.53,0, []],
                ['Silver nitrate',                              'g',   43.14, 0, []],
                ['Silver sulfate',                              'g',   45,    0, []],
                ['Sodium acetat trihydrate',                    'g',   1300,  0, []],
                ['Sodium azide',                                null,  null,  0, []],
                ['Sodium borohyride',                           'g',   170,   0, []],
                ['Sodium Carbonate',                            'g',   750,   0, []],
                ['Sodium chloride',                             'g',   1599.41,0, []],
                ['Sodium dihydrogen phospate dihydrate',        'g',   480,   0, []],
                ['Sodium fluoride',                             'g',   250,   0, []],
                ['Sodium hydrogen Carbonate',                   'g',   900,   0, []],
                ['Sodium hydrogen sulfite',                     'ml',  1000,  0, []],
                ['Sodium hydroxide',                            'g',   3583.75,0, []],
                ['Sodium nitrite',                              'g',   850,   0, []],
                ['Sodium nitroprusside dihydrate',              'g',   160,   0, []],
                ['Sodium sulfate',                              'g',   1495.87,0, []],
                ['Sodium sulfite',                              'g',   1000,  0, []],
                ['Sodium tetraborate',                          'g',   340,   0, []],
                ['Sodium tetraphenyl borate',                   'g',   74,    0, []],
                ['Sodium thiosulfate',                          'g',   1000,  0, []],
                ['Starch',                                      null,  null,  0, []],
                ['Stearic acid',                                'g',   1740,  0, []],
                ['Strontium nitrate',                           'g',   150,   0, []],
                ['Sulfanilamide',                               'g',   102,   0, []],
                ['Sulfanilic acid',                             null,  null,  0, []],
                ['Sulphuric acid',                              'ml',  10585.5,0,[]],
                ['Thiocetamide',                                'g',   45,    0, []],
                ['Tin (II) chloride',                           'g',   500,   0, []],
                ['Titriplex',                                   null,  null,  0, []],
                ['Titriplex I',                                 'g',   100,   0, []],
                ['Titriplex II',                                null,  null,  0, []],
                ['Titriplex III',                               null,  null,  0, []],
                ['Tri-natriumphosphat-dodecahhydrate',          null,  null,  0, []],
                ['Trisodium citrate dihydrate',                 'g',   3000,  0, []],
                ['Tri-Sodium Phosphate dodecahydrat',           'g',   500,   0, []],
                ['Wolframatophosphosaure hydrate',              'g',   40,    0, []],
                ['Xylene',                                      'ml',  15000, 0, []],
                ['Zirkon (IV) Oxidchlorid-Octahydrat',         'g',   105,   0, []],
                ['Zinc acetate dihydrate',                      'g',   170,   0, []],
                ['Zinc sulfate',                                null,  null,  0, []],
                ['Zinc sulfate heptahydrate',                   'g',   900,   0, []],
            ],

            // ══════════════════════════════════════════════════════
            // JUNI 2026
            // ══════════════════════════════════════════════════════
            '2026-06' => [
                ['1,10 - phenanthroline chloride monohydrate',  'g',   20,    0,    []],
                ['1,10 - phenanthroline monohydrate',           'g',   1.1,   0,    []],
                ['1,8-Dihydroxy-2-(4-Sulfophenylazo)-naphthalene-3,6-disulfonic acid trisodium salt','g',5,0,[]],
                ['1,5-Diphenylcarbazide',                       'g',   40,    0,    []],
                ['1-Amino-2-hydroxide-4-naphtalene sulforic acid','g', 20,    0,    []],
                ['1-Butanol',                                   'ml',  2500,  0,    []],
                ['1-Naphtholbenzine',                           'g',   2,     0,    []],
                ['4-amino-2,3-dimethyl-1phenyl-3-pyrazolin-5-one','g', 3,     0,    []],
                ['Acetic acid (glacial) 100%',                  'ml',  13500, 60,   ['2026-06-08'=>[20,20,null,'Tyas'],'2026-06-21'=>[20,null,null,'Tyas']]],
                ['Acetone p.a',                                 'ml',  10000, 0,    []],
                ['Acetone teknis',                              null,  null,  0,    []],
                ['Alizarin -3- methylamine-N,N diacetic acid dihydrate','g',1,0,    []],
                ['Alizarin Red indicator',                      'g',   24,    0,    []],
                ['Alkylbenzyl dimethylammonium chloride',        'g',   200,   0,    []],
                ['Alumunium foil',                              null,  null,  0,    []],
                ['Aluminium hydroxide',                         'g',   1950,  22.5, ['2026-06-01'=>[22.5,null,null,'Jihan'],'2026-06-03'=>[22.5,null,null,'Nur Janah']]],
                ['Aluminium kalium sulfat dodecahydrat',        'g',   500,   0,    []],
                ['Amidosulfuris acid',                          'g',   160,   0,    []],
                ['Ammonia solution 25 %',                       'ml',  1927.5,0,    []],
                ['Ammonium acetate',                            'g',   1750,  0,    []],
                ['Ammonium fluoride',                           'g',   240,   0,    []],
                ['Ammonium heptamolybdate tetrahydrate',        'g',   500,   0,    []],
                ['Ammonium iron (III) sulfate dodecahydrate',   'g',   12080, 0,    []],
                ['Amonium chloride',                            'g',   935.5, 0,    []],
                ['Amonium monovanadate',                        'g',   197,   0,    []],
                ['Aquabides',                                   'ml',  15000, 0,    []],
                ['Asam salisilat teknis',                       'g',   302,   0,    []],
                ['Asam sulfamat',                               'g',   3,     0,    []],
                ['Barbituric acid',                             'g',   3,     0,    []],
                ['Barium acetat',                               'g',   200,   0,    []],
                ['Barium chloride dihydrate',                   null,  null,  0,    []],
                ['Biuret wasserfrei',                           null,  null,  0,    []],
                ['Boric acid',                                  'g',   500,   0,    []],
                ['Bromocresol green indicator',                 'g',   7,     0,    []],
                ['Brucine',                                     'g',   120,   0,    []],
                ['Cadmium sulfat hydrate',                      'g',   120,   0,    []],
                ['Calcium carbonate',                           'g',   250,   0,    []],
                ['Calcium hypochlorite',                        'g',   80,    0,    []],
                ['Cerium (III) nitratehex-hydrate',             'g',   30,    0,    []],
                ['Chloramin T trihydrate',                      'g',   470,   0,    []],
                ['Chloroform',                                  null,  null,  0,    []],
                ['Chromatropic Acid disodium salt',             'g',   44,    0,    []],
                ['Chromium (VI) oxide',                         'g',   370,   0,    []],
                ['Citric acid monohydrate',                     'g',   500,   0,    []],
                ['Cobalt (II) chloride hexahydrate',            'g',   90,    0,    []],
                ['Copper (II) sulfate pentahydrate',            'g',   1695.94,0,   []],
                ['Curcumine',                                   'g',   3,     0,    []],
                ['Cyclohexane',                                 'ml',  5000,  0,    []],
                ['D (+) Glucose anhydrous for biochemistry',    null,  null,  0,    []],
                ['Devarda alloy',                               'g',   370,   0,    []],
                ['Di-ammonium oxalate monohydrate',             'g',   462,   0,    []],
                ['Di-amonium hydrogen phosphate',               'g',   450,   0,    []],
                ['Dikalium hydrogen phosphat',                  'g',   600,   0,    []],
                ['Dimedone',                                    'g',   49,    0,    []],
                ['Disodium hydrogen phosphate dodecahydrate',   'g',   500,   0,    []],
                ['Disodium hydrogen phosphate heptahydrate',    'g',   150,   0,    []],
                ['Di-sodium oxalate',                           'g',   250,   0,    []],
                ['Dodecyl sulfate sodium salt',                 'g',   180,   0,    []],
                ['Eisen (II) sulfate-heptahydrat',             null,  null,  0,    []],
                ['Eosin Y (Yellowish) CI 45380',               'g',   15,    0,    []],
                ['Erichrome cyanine R CI 4380',                'g',   25,    0,    []],
                ['Ethanol',                                     'ml',  10200, 0,    []],
                ['Ethanol absolut',                             'ml',  200,   0,    []],
                ['Ferroin indicator solution',                  null,  null,  0,    []],
                ['Formaldehyde solution 37%',                   null,  null,  0,    []],
                ['Gelatine',                                    'g',   950,   0,    []],
                ['Hexamethylene-tetramine',                     'g',   100,   0,    []],
                ['Hydrazinium sulfate',                         'g',   170,   0,    []],
                ['Hydrochloric acid 37%',                       'ml',  18455, 0,    []],
                ['Hydrochloric acid fuming 37%',                'ml',  5000,  0,    []],
                ['Hydrogen peroxide 30%',                       'ml',  2500,  0,    []],
                ['Hydroxlamine hydrochloride',                  null,  null,  0,    []],
                ['Hydroxylammonium chloride',                   'g',   220,   0,    []],
                ['Hydroxylammonium sulfate',                    'g',   400,   0,    []],
                ['Indigocarmin',                                'g',   25,    0,    []],
                ['Iodine',                                      'g',   160,   0,    []],
                ['Iron (III) Chloride',                         'g',   70,    0,    []],
                ['Iron (II) Sulfate Heptahydrate',              'g',   100,   0,    []],
                ['Iron test',                                   'test',300,   0,    []],
                ['Isoamyl alkohol',                             'ml',  900,   0,    []],
                ['Isobutyl methyl ketone',                      null,  null,  0,    []],
                ['Kalium bromat',                               'g',   50,    0,    []],
                ['Kalium chlorat',                              'g',   300,   0,    []],
                ['Kalium iodidat',                              null,  null,  0,    []],
                ['Kaliumantimon (III)-oxidtartrat-hemihydrat',  'g',   200,   0,    []],
                ['L (+) Asorbic Acid',                         'g',   235,   0,    []],
                ['Lanthanum (III) chloride heptahydrate 98%',  'g',   80,    0,    []],
                ['Lanthanum nitrate hexahydrate',               'g',   10,    0,    []],
                ['Lead (II) acetate trihydrate',                'g',   230,   0,    []],
                ['Lead (II) oxide',                             'g',   250,   0,    []],
                ['L-Histidine monohydrate chloride monohydrate',null,  null,  0,    []],
                ['Magnesium (II) sulfate monohydrate',          null,  null,  0,    []],
                ['Magnesium chloride hexahydrate',              'g',   800,   0,    []],
                ['Magnesium oxide',                             'g',   76,    0,    []],
                ['Manganese (II) Sulfate Monohydrate',          'g',   253,   0,    []],
                ['Manganese test',                              null,  null,  0,    []],
                ['Mercury (II) chloride',                       'g',   10,    0,    []],
                ['Mercury (II) iodide',                         'g',   40,    0,    []],
                ['Mercury (II) oxide',                          'g',   40,    0,    []],
                ['Mercury (II) sulfate',                        'g',   500,   0,    []],
                ['Mercury (II) thiocyanate',                    'g',   25,    0,    []],
                ['Methanol',                                    'ml',  2500,  0,    []],
                ['Methyl Purple Indicator Solution 1 g/L',      'ml',  500,   0,    []],
                ['Methyl red (CI 13020)',                       'g',   35,    0,    []],
                ['Methyl red sodium salt (CI 13020)',           'g',   44,    0,    []],
                ['Methylenblue',                                'g',   5,     0,    []],
                ['N-(1-Naphythyl) ethylenediamine dihydro-chloride','g',180,  0,   []],
                ['N,N-diethyl-1,4 phenyle diammonium sulfat',  'g',   200,   0,    []],
                ['N,N-dimethyl-1,4 phenylene diamonium dichloride','g',50,    0,   []],
                ['N,N-Dimethyl-1,4 phenyl-enediamine oxalate', null,  null,  0,    []],
                ['n-Amylalkohol',                               'ml',  900,   0,    []],
                ['Naphtholbenzein',                             'g',   3,     0,    []],
                ['Natrium fluoride',                            'g',   250,   0,    []],
                ['Natrium molibdat.dihidrat',                   'g',   30,    0,    []],
                ['n-heptane',                                   null,  null,  0,    []],
                ['n-Hexadecane',                                'ml',  500,   0,    []],
                ['Nickel (II) nitrate hexahydrate',             'g',   100,   0,    []],
                ['Nitric acid 65%',                             'ml',  17880, 0,    []],
                ['Ortho-Phosphoric acid 85%',                   null,  null,  0,    []],
                ['Oxalic acid dihydrate',                       'g',   500,   0,    []],
                ['Pararosanline (chloride) CI 42500',           null,  null,  0,    []],
                ['Perochloric acid 70-72%',                     'ml',  4500,  0,    []],
                ['Phenol',                                      'g',   100,   0,    []],
                ['Phenol Red ( Phenol sulfonphthalein)',         'g',   0.4,   0,    []],
                ['Phenol red indicator',                        'g',   3,     0,    []],
                ['Phenolphathalein indicator',                  null,  null,  0,    []],
                ['Potassium chloride',                          'g',   600,   0,    []],
                ['Potassium chromate',                          'g',   830,   0,    []],
                ['Potassium cyanide',                           'g',   800,   0,    []],
                ['Potassium dichromate',                        'g',   570,   0,    []],
                ['Potassium dihydrogen phosphate',              null,  null,  0,    []],
                ['Potassium hexacynoferrate (II) trihydrate',   'g',   300,   0,    []],
                ['Potassium hexxchloroplatirale (IV)',           'g',   100,   0,    []],
                ['Potassium hydrogen phthalate',                'g',   230,   0,    []],
                ['Potassium hydroxide',                         null,  null,  0,    []],
                ['Potassium Iodide',                            'g',   1200,  0,    []],
                ['Potassium nitrate',                           'g',   1900,  0,    []],
                ['Potassium permanganat',                       null,  null,  0,    []],
                ['Potassium peroxodisulfate',                   'g',   250,   0,    []],
                ['Potassium sodium tartrate tetrahydrate',       'g',   1550,  0,    []],
                ['Potassium Sulfate',                           'g',   2500,  0,    []],
                ['Pyrroliodine-1-dithiocarboxylic acid ammonium salt','g',8,  0,   []],
                ['Salicylic Acid',                              null,  null,  0,    []],
                ['Selenium reagent mixture',                    'g',   698.53,0,    []],
                ['Silver nitrate',                              'g',   43.14, 0,    []],
                ['Silver sulfate',                              'g',   45,    0,    []],
                ['Sodium acetat trihydrate',                    'g',   1300,  0,    []],
                ['Sodium azide',                                null,  null,  0,    []],
                ['Sodium borohyride',                           'g',   170,   0,    []],
                ['Sodium Carbonate',                            'g',   750,   0,    []],
                ['Sodium chloride',                             'g',   1599.41,0,   []],
                ['Sodium dihydrogen phospate dihydrate',        'g',   480,   0,    []],
                ['Sodium fluoride',                             'g',   250,   0,    []],
                ['Sodium hydrogen Carbonate',                   'g',   900,   0,    []],
                ['Sodium hydrogen sulfite',                     'ml',  1000,  0,    []],
                ['Sodium hydroxide',                            'g',   3583.75,0,   []],
                ['Sodium nitrite',                              'g',   850,   0,    []],
                ['Sodium nitroprusside dihydrate',              'g',   160,   0,    []],
                ['Sodium sulfate',                              'g',   1495.87,0,   []],
                ['Sodium sulfite',                              'g',   1000,  0,    []],
                ['Sodium tetraborate',                          'g',   340,   0,    []],
                ['Sodium tetraphenyl borate',                   'g',   74,    0,    []],
                ['Sodium thiosulfate',                          'g',   1000,  0,    []],
                ['Starch',                                      null,  null,  0,    []],
                ['Stearic acid',                                'g',   1740,  0,    []],
                ['Strontium nitrate',                           'g',   150,   0,    []],
                ['Sulfanilamide',                               'g',   102,   0,    []],
                ['Sulfanilic acid',                             null,  null,  0,    []],
                ['Sulphuric acid',                              'ml',  10585.5,0,   []],
                ['Thiocetamide',                                'g',   45,    0,    []],
                ['Tin (II) chloride',                           'g',   500,   0,    []],
                ['Titriplex',                                   null,  null,  0,    []],
                ['Titriplex I',                                 'g',   100,   0,    []],
                ['Titriplex II',                                null,  null,  0,    []],
                ['Titriplex III',                               null,  null,  0,    []],
                ['Tri-natriumphosphat-dodecahhydrate',          null,  null,  0,    []],
                ['Trisodium citrate dihydrate',                 'g',   3000,  0,    []],
                ['Tri-Sodium Phosphate dodecahydrat',           'g',   500,   0,    []],
                ['Wolframatophosphosaure hydrate',              'g',   40,    0,    []],
                ['Xylene',                                      'ml',  15000, 0,    []],
                ['Zirkon (IV) Oxidchlorid-Octahydrat',         'g',   105,   0,    []],
                ['Zinc acetate dihydrate',                      'g',   170,   0,    []],
                ['Zinc sulfate',                                null,  null,  0,    []],
                ['Zinc sulfate heptahydrate',                   'g',   900,   0,    []],
            ],

            // ══════════════════════════════════════════════════════
            // JULI 2026
            // ══════════════════════════════════════════════════════
            '2026-07' => [
                ['1,10 - phenanthroline chloride monohydrate',  'g',   10,    0,    []],
                ['1,10 - phenanthroline monohydrate',           'g',   1.1,   0,    []],
                ['1,8-Dihydroxy-2-(4-Sulfophenylazo)-naphthalene-3,6-disulfonic acid trisodium salt','g',5,0,[]],
                ['1,5-Diphenylcarbazide',                       'g',   40,    0,    []],
                ['1-Amino-2-hydroxide-4-naphtalene sulforic acid','g', 20,    0,    []],
                ['1-Butanol',                                   'ml',  2500,  0,    []],
                ['1-Naphtholbenzine',                           'g',   2,     0,    []],
                ['4-amino-2,3-dimethyl-1phenyl-3-pyrazolin-5-one','g', 3,     0,    []],
                ['Acetic acid (glacial) 100%',                  'ml',  13440, 60,   ['2026-07-08'=>[20,20,null,'Tyas'],'2026-07-21'=>[20,null,null,'Tyas']]],
                ['Acetone p.a',                                 'ml',  10000, 0,    []],
                ['Acetone teknis',                              null,  null,  0,    []],
                ['Alizarin -3- methylamine-N,N diacetic acid dihydrate','g',1,0,    []],
                ['Alizarin Red indicator',                      'g',   24,    0,    []],
                ['Alkylbenzyl dimethylammonium chloride',        'g',   200,   0,    []],
                ['Alumunium foil',                              null,  null,  0,    []],
                ['Aluminium hydroxide',                         'g',   1927.5,22.5, ['2026-07-01'=>[22.5,null,null,'Jihan'],'2026-07-03'=>[22.5,null,null,'Nur Janah']]],
                ['Aluminium kalium sulfat dodecahydrat',        'g',   500,   0,    []],
                ['Amidosulfuris acid',                          'g',   160,   0,    []],
                ['Ammonia solution 25 %',                       'ml',  1927.5,0,    []],
                ['Ammonium acetate',                            'g',   1750,  0,    []],
                ['Ammonium fluoride',                           'g',   240,   0,    []],
                ['Ammonium heptamolybdate tetrahydrate',        'g',   500,   0,    []],
                ['Ammonium iron (III) sulfate dodecahydrate',   'g',   12080, 0,    []],
                ['Amonium chloride',                            'g',   935.5, 0,    []],
                ['Amonium monovanadate',                        'g',   197,   0,    []],
                ['Aquabides',                                   'ml',  15000, 0,    []],
                ['Asam salisilat teknis',                       'g',   302,   0,    []],
                ['Asam sulfamat',                               'g',   3,     0,    []],
                ['Barbituric acid',                             'g',   3,     0,    []],
                ['Barium acetat',                               'g',   200,   0,    []],
                ['Barium chloride dihydrate',                   null,  null,  0,    []],
                ['Biuret wasserfrei',                           null,  null,  0,    []],
                ['Boric acid',                                  'g',   500,   0,    []],
                ['Bromocresol green indicator',                 'g',   7,     0,    []],
                ['Brucine',                                     'g',   120,   0,    []],
                ['Cadmium sulfat hydrate',                      'g',   120,   0,    []],
                ['Calcium carbonate',                           'g',   250,   0,    []],
                ['Calcium hypochlorite',                        'g',   80,    0,    []],
                ['Cerium (III) nitratehex-hydrate',             'g',   30,    0,    []],
                ['Chloramin T trihydrate',                      'g',   470,   0,    []],
                ['Chloroform',                                  null,  null,  0,    []],
                ['Chromatropic Acid disodium salt',             'g',   44,    0,    []],
                ['Chromium (VI) oxide',                         'g',   370,   0,    []],
                ['Citric acid monohydrate',                     'g',   500,   0,    []],
                ['Cobalt (II) chloride hexahydrate',            'g',   90,    0,    []],
                ['Copper (II) sulfate pentahydrate',            'g',   1695.94,0,   []],
                ['Curcumine',                                   'g',   3,     0,    []],
                ['Cyclohexane',                                 'ml',  5000,  0,    []],
                ['D (+) Glucose anhydrous for biochemistry',    null,  null,  0,    []],
                ['Devarda alloy',                               'g',   370,   0,    []],
                ['Di-ammonium oxalate monohydrate',             'g',   462,   0,    []],
                ['Di-amonium hydrogen phosphate',               'g',   450,   0,    []],
                ['Dikalium hydrogen phosphat',                  'g',   600,   0,    []],
                ['Dimedone',                                    'g',   49,    0,    []],
                ['Disodium hydrogen phosphate dodecahydrate',   'g',   500,   0,    []],
                ['Disodium hydrogen phosphate heptahydrate',    'g',   150,   0,    []],
                ['Di-sodium oxalate',                           'g',   250,   0,    []],
                ['Dodecyl sulfate sodium salt',                 'g',   180,   0,    []],
                ['Eisen (II) sulfate-heptahydrat',             null,  null,  0,    []],
                ['Eosin Y (Yellowish) CI 45380',               'g',   15,    0,    []],
                ['Erichrome cyanine R CI 4380',                'g',   25,    0,    []],
                ['Ethanol',                                     'ml',  10200, 0,    []],
                ['Ethanol absolut',                             'ml',  200,   0,    []],
                ['Ferroin indicator solution',                  null,  null,  0,    []],
                ['Formaldehyde solution 37%',                   null,  null,  0,    []],
                ['Gelatine',                                    'g',   950,   0,    []],
                ['Hexamethylene-tetramine',                     'g',   100,   0,    []],
                ['Hydrazinium sulfate',                         'g',   170,   0,    []],
                ['Hydrochloric acid 37%',                       'ml',  18455, 0,    []],
                ['Hydrochloric acid fuming 37%',                'ml',  5000,  0,    []],
                ['Hydrogen peroxide 30%',                       'ml',  2500,  0,    []],
                ['Hydroxlamine hydrochloride',                  null,  null,  0,    []],
                ['Hydroxylammonium chloride',                   'g',   220,   0,    []],
                ['Hydroxylammonium sulfate',                    'g',   400,   0,    []],
                ['Indigocarmin',                                'g',   25,    0,    []],
                ['Iodine',                                      'g',   160,   0,    []],
                ['Iron (III) Chloride',                         'g',   70,    0,    []],
                ['Iron (II) Sulfate Heptahydrate',              'g',   100,   0,    []],
                ['Iron test',                                   'test',300,   0,    []],
                ['Isoamyl alkohol',                             'ml',  900,   0,    []],
                ['Isobutyl methyl ketone',                      null,  null,  0,    []],
                ['Kalium bromat',                               'g',   50,    0,    []],
                ['Kalium chlorat',                              'g',   300,   0,    []],
                ['Kalium iodidat',                              null,  null,  0,    []],
                ['Kaliumantimon (III)-oxidtartrat-hemihydrat',  'g',   200,   0,    []],
                ['L (+) Asorbic Acid',                         'g',   235,   0,    []],
                ['Lanthanum (III) chloride heptahydrate 98%',  'g',   80,    0,    []],
                ['Lanthanum nitrate hexahydrate',               'g',   10,    0,    []],
                ['Lead (II) acetate trihydrate',                'g',   230,   0,    []],
                ['Lead (II) oxide',                             'g',   250,   0,    []],
                ['L-Histidine monohydrate chloride monohydrate',null,  null,  0,    []],
                ['Magnesium (II) sulfate monohydrate',          null,  null,  0,    []],
                ['Magnesium chloride hexahydrate',              'g',   800,   0,    []],
                ['Magnesium oxide',                             'g',   76,    0,    []],
                ['Manganese (II) Sulfate Monohydrate',          'g',   253,   0,    []],
                ['Manganese test',                              null,  null,  0,    []],
                ['Mercury (II) chloride',                       'g',   10,    0,    []],
                ['Mercury (II) iodide',                         'g',   40,    0,    []],
                ['Mercury (II) oxide',                          'g',   40,    0,    []],
                ['Mercury (II) sulfate',                        'g',   500,   0,    []],
                ['Mercury (II) thiocyanate',                    'g',   25,    0,    []],
                ['Methanol',                                    'ml',  2500,  0,    []],
                ['Methyl Purple Indicator Solution 1 g/L',      'ml',  500,   0,    []],
                ['Methyl red (CI 13020)',                       'g',   35,    0,    []],
                ['Methyl red sodium salt (CI 13020)',           'g',   44,    0,    []],
                ['Methylenblue',                                'g',   5,     0,    []],
                ['N-(1-Naphythyl) ethylenediamine dihydro-chloride','g',180,  0,   []],
                ['N,N-diethyl-1,4 phenyle diammonium sulfat',  'g',   200,   0,    []],
                ['N,N-dimethyl-1,4 phenylene diamonium dichloride','g',50,    0,   []],
                ['N,N-Dimethyl-1,4 phenyl-enediamine oxalate', null,  null,  0,    []],
                ['n-Amylalkohol',                               'ml',  900,   0,    []],
                ['Naphtholbenzein',                             'g',   3,     0,    []],
                ['Natrium fluoride',                            'g',   250,   0,    []],
                ['Natrium molibdat.dihidrat',                   'g',   30,    0,    []],
                ['n-heptane',                                   null,  null,  0,    []],
                ['n-Hexadecane',                                'ml',  500,   0,    []],
                ['Nickel (II) nitrate hexahydrate',             'g',   100,   0,    []],
                ['Nitric acid 65%',                             'ml',  17880, 0,    []],
                ['Ortho-Phosphoric acid 85%',                   null,  null,  0,    []],
                ['Oxalic acid dihydrate',                       'g',   500,   0,    []],
                ['Pararosanline (chloride) CI 42500',           null,  null,  0,    []],
                ['Perochloric acid 70-72%',                     'ml',  4500,  0,    []],
                ['Phenol',                                      'g',   100,   0,    []],
                ['Phenol Red ( Phenol sulfonphthalein)',         'g',   0.4,   0,    []],
                ['Phenol red indicator',                        'g',   3,     0,    []],
                ['Phenolphathalein indicator',                  null,  null,  0,    []],
                ['Potassium chloride',                          'g',   600,   0,    []],
                ['Potassium chromate',                          'g',   830,   0,    []],
                ['Potassium cyanide',                           'g',   800,   0,    []],
                ['Potassium dichromate',                        'g',   570,   0,    []],
                ['Potassium dihydrogen phosphate',              null,  null,  0,    []],
                ['Potassium hexacynoferrate (II) trihydrate',   'g',   300,   0,    []],
                ['Potassium hexxchloroplatirale (IV)',           'g',   100,   0,    []],
                ['Potassium hydrogen phthalate',                'g',   230,   0,    []],
                ['Potassium hydroxide',                         null,  null,  0,    []],
                ['Potassium Iodide',                            'g',   1200,  0,    []],
                ['Potassium nitrate',                           'g',   1900,  0,    []],
                ['Potassium permanganat',                       null,  null,  0,    []],
                ['Potassium peroxodisulfate',                   'g',   250,   0,    []],
                ['Potassium sodium tartrate tetrahydrate',       'g',   1550,  0,    []],
                ['Potassium Sulfate',                           'g',   2500,  0,    []],
                ['Pyrroliodine-1-dithiocarboxylic acid ammonium salt','g',8,  0,   []],
                ['Salicylic Acid',                              null,  null,  0,    []],
                ['Selenium reagent mixture',                    'g',   698.53,0,    []],
                ['Silver nitrate',                              'g',   43.14, 0,    []],
                ['Silver sulfate',                              'g',   45,    0,    []],
                ['Sodium acetat trihydrate',                    'g',   1300,  0,    []],
                ['Sodium azide',                                null,  null,  0,    []],
                ['Sodium borohyride',                           'g',   170,   0,    []],
                ['Sodium Carbonate',                            'g',   750,   0,    []],
                ['Sodium chloride',                             'g',   1599.41,0,   []],
                ['Sodium dihydrogen phospate dihydrate',        'g',   480,   0,    []],
                ['Sodium fluoride',                             'g',   250,   0,    []],
                ['Sodium hydrogen Carbonate',                   'g',   900,   0,    []],
                ['Sodium hydrogen sulfite',                     'ml',  1000,  0,    []],
                ['Sodium hydroxide',                            'g',   3583.75,0,   []],
                ['Sodium nitrite',                              'g',   850,   0,    []],
                ['Sodium nitroprusside dihydrate',              'g',   160,   0,    []],
                ['Sodium sulfate',                              'g',   1495.87,0,   []],
                ['Sodium sulfite',                              'g',   1000,  0,    []],
                ['Sodium tetraborate',                          'g',   340,   0,    []],
                ['Sodium tetraphenyl borate',                   'g',   74,    0,    []],
                ['Sodium thiosulfate',                          'g',   1000,  0,    []],
                ['Starch',                                      null,  null,  0,    []],
                ['Stearic acid',                                'g',   1740,  0,    []],
                ['Strontium nitrate',                           'g',   150,   0,    []],
                ['Sulfanilamide',                               'g',   102,   0,    []],
                ['Sulfanilic acid',                             null,  null,  0,    []],
                ['Sulphuric acid',                              'ml',  10585.5,0,   []],
                ['Thiocetamide',                                'g',   45,    0,    []],
                ['Tin (II) chloride',                           'g',   500,   0,    []],
                ['Titriplex',                                   null,  null,  0,    []],
                ['Titriplex I',                                 'g',   100,   0,    []],
                ['Titriplex II',                                null,  null,  0,    []],
                ['Titriplex III',                               null,  null,  0,    []],
                ['Tri-natriumphosphat-dodecahhydrate',          null,  null,  0,    []],
                ['Trisodium citrate dihydrate',                 'g',   3000,  0,    []],
                ['Tri-Sodium Phosphate dodecahydrat',           'g',   500,   0,    []],
                ['Wolframatophosphosaure hydrate',              'g',   40,    0,    []],
                ['Xylene',                                      'ml',  15000, 0,    []],
                ['Zirkon (IV) Oxidchlorid-Octahydrat',         'g',   105,   0,    []],
                ['Zinc acetate dihydrate',                      'g',   170,   0,    []],
                ['Zinc sulfate',                                null,  null,  0,    []],
                ['Zinc sulfate heptahydrate',                   'g',   900,   0,    []],
            ],
        ];
    }
}
